version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql_tainacan
    ports:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - "${PATH}/mysql:/var/lib/mysql"

  wordpress:
   image: walisonjosededeus/tainacan:3.2
   container_name: wordpress_tainacan
   ports:
      - "80:80"
      - "443:443"
   restart: always
   environment:
      WORDPRESS_DB_HOST: ${MYSQL_DB_HOST}:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
   
   volumes:
    - "${PATH}/uploads:/var/www/html/wp-content/uploads"
    - "${PATH}/tainacan-theme:/files/tainacan-theme"
    - "${PATH}/themes:/var/www/html/wp-content/themes"
    - '${PATH}/plugins:/var/www/html/wp-content/plugins"
    #- ${PATH}/docker_configs/default_host:/etc/apache2/sites-available/
    #- ${PATH}/certificados_medilab:/etc/ssl/medialab/
