version: '3'
services:  
  banco:
     image: mysql:5.7
     ports:
        - "3306:3306"
     container_name: db_tainacan
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

  parede:
     build: .
     ports:
        - "80:80"
     restart: always
     links:
       - banco:db_tainacan
