version: '3.3'
services:
  db:
    image: mysql:5.7
    #container_name: mysql_tainacan
    ports:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
     - "${document_root}/mysql:/var/lib/mysql"
     
  wordpress:
   image: walisonjosededeus/tainacan:3.3.1
   #container_name: wordpress_tainacan
   ports:
     - "${PORT_HTTP}:80"
     - "${PORT_HTTPS}:443"
     -  "25"
   restart: always
   environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      WORDPRESS_DB_PASSWORD: ${MYSQL_USER_PASSWORD}
     # WORDPRESS_URL_SITE: ${WORDPRESS_URL_SITE}
     # WORDPRESS_TITLE_SITE: ${WORDPRESS_TITLE_SITE}
      #WORDPRESS_ADMIN_SITE: ${WORDPRESS_ADMIN_SITE}
     # WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
     # WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      
   
   volumes:
    - "${document_root}:/files"
    #- "${document_root}/wp-config.php:/var/www/html/wp-config.php"
    - "${document_root}/docker_configs/default_host:/etc/apache2/sites-available/"
    - "${document_root}/certificados_medilab:/etc/ssl/medialab/"
    - "${FTP_DIR}:/ftp"
