version: '3'
services:
 db:
   container_name: db_tainacan
   image: mysql:latest
   ports:
   - "3306:3306"
   environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
 tainacan:
    image: walisonjosededeus/tainacan_compose:1.0
    container_name: web_tainacan
    ports:
     - "80:80"
    links:
     - db
